// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hinwnssmzddddkfkmsgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpbnduc3NtemRkZGRrZmttc2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1OTczODAsImV4cCI6MjA3NzE3MzM4MH0.83gV53zaX7YmyUmdvLNUR-d16G3x3aLvgr3ZDkQrw00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);